### ISSUE TITLE
Ground clearance

### ISSUE THREAD

**Issue by avenjamin** [Cat-Lips/GodotSharp.BuildingBlocks#2]
Oi Dazza!
Can you add some cars with better ground clearance - i keep getting hung up on the terrain.

**Comment by Cat-Lips** [comment]
Hi Ben.

Definitely!  Playability still needs a bit of work, but I think this will be a good quick one to fix.

At the moment this repo is just a collection of interesting looking online tutorials loosely coupled into the beginnings of a reusable game related framework, but hey, at least it works! ;)

Thanks for checking it out :)

**Comment by avenjamin** [comment]
Perhaps a capture the flag/race to the flag style game could be fun - each player has their own flag to get to or there's a single one.

Or race to collect as many flags or pass through all the check points.

If there was a larger proportion of water then you could switch it up to use boats/jetskis/submarines/etc

Lots of possibilities.

Keep it up :)

**Comment by Cat-Lips** [comment]
Hi Ben.

The current pre-release should help with ground clearance.
(I've included an in-game vehicle editor for shyts and gaggles...)
Some simple gameplay elements will be next.

Cheers :)
